services:
  - type: web
    name: thinkly-web
    env: python
    region: oregon
    plan: free
    repo: https://github.com/Tejaswi410/Thinkly
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn Thinkly.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
    

databases:
  - name: thinkly-db
    engine: POSTGRESQL
    version: 15
    plan: free
    region: oregon
