services:
  - type: web
    name: thinkly
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Thinkly.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12

