services:
  - type: web
    name: thinkly
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn Thinkly.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
    
databases:
  - name: thinkly-db
    plan: free
    databaseName: thinkly
    user: thinkly